name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/local-s3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Install and run ipfs
      run: ./install-run-ipfs.sh
    - name: Build and Package
      run: mvn package -Dmaven.test.skip=true
    - name: Run tests
      timeout-minutes: 10
      run: mvn test
