name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Install and run ipfs
      run: ./install-run-ipfs.sh
    - name: Build and Package
      run: mvn package -Dmaven.test.skip=true
    - name: Run tests
      timeout-minutes: 10
      run: mvn test
